/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/eyeball.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials['Material.001']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Torus.geometry}
        material={materials.Material}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.03, 0.02, 0.02]}>
        <mesh
          geometry={nodes.Sphere001.geometry}
          material={materials['Material.005']}
          position={[-0.02, 0.15, -0.01]}
          rotation={[Math.PI, 0, 0]}
          scale={[0.52, 0.9, 0.72]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/eyeball.gltf')
